"""Add IMPORT to ExpenseSource

Revision ID: 755612d5825b
Revises: c0462a9b49cf
Create Date: 2025-12-08 11:17:34.524008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '755612d5825b'
down_revision: Union[str, None] = 'c0462a9b49cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Manual addition of enum value because Alembic doesn't auto-detect it
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE expensesource ADD VALUE 'IMPORT'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
