"""add emoji to budgets and receipt_url to expenses

Revision ID: bf2e4ef639e9
Revises: cdeaffd2b313
Create Date: 2025-11-25 21:24:13.981417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf2e4ef639e9'
down_revision: Union[str, None] = 'cdeaffd2b313'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('emoji', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('receipt_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'receipt_url')
    op.drop_column('budgets', 'emoji')
    # ### end Alembic commands ###
