"""add_import_to_expense_source

Revision ID: c0462a9b49cf
Revises: bf2e4ef639e9
Create Date: 2025-11-28 12:49:41.914430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0462a9b49cf'
down_revision: Union[str, None] = 'bf2e4ef639e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE expensesource ADD VALUE 'import'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
