"""add name and category_id to budgets

Revision ID: cdeaffd2b313
Revises: e15978e94003
Create Date: 2025-11-25 20:41:59.534240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdeaffd2b313'
down_revision: Union[str, None] = 'e15978e94003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budgets', sa.Column('name', sa.String(), nullable=True))
    op.add_column('budgets', sa.Column('category_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'budgets', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budgets', type_='foreignkey')
    op.drop_column('budgets', 'category_id')
    op.drop_column('budgets', 'name')
    # ### end Alembic commands ###
